"use client";
import { useId, useRef, useState } from "react";
import { analyzeIban, type IbanResult } from "@/lib/iban";
import { parseIbanInput, resultsToCsv, MAX_CSV_BYTES } from "@/lib/csv";
import { track } from "@/lib/analytics";
import { Icon } from "./icon";
import { useUi, useLocale } from "./locale-provider";
import { localizeResult } from "@/lib/iban-display";
export function BulkValidator() {
  const ui = useUi();
  const { locale } = useLocale();
  const id=useId();const fileInput=useRef<HTMLInputElement>(null);
  const [text,setText]=useState("");const [results,setResults]=useState<IbanResult[]|null>(null);const [error,setError]=useState("");const [fileName,setFileName]=useState("");
  function run(e:React.FormEvent){e.preventDefault();try{const entries=parseIbanInput(text);if(!entries.length){setError(ui.bulk.empty);return;}setResults(entries.map(analyzeIban));setError("");track("iban_scan");}catch(e){setError(e instanceof Error&&e.message.includes("free limit")?ui.bulk.limit:locale==="en"&&e instanceof Error?e.message:ui.bulk.fileError+" "+ui.bulk.csvHelp);setResults(null);}}
  async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(file.size>MAX_CSV_BYTES || !/\.csv$/i.test(file.name)){setError(ui.bulk.fileError);e.target.value="";return;}try{setText(await file.text());setFileName(file.name);setResults(null);setError("");track("csv_upload");}catch{setError(ui.bulk.fileError);}finally{e.target.value="";}}
  function download(){if(!results)return;const url=URL.createObjectURL(new Blob([resultsToCsv(results.map(r=>localizeResult(r,locale)))],{type:"text/csv;charset=utf-8;"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="ibanscan-results.csv";document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <div className="bulk-tool"><section className="card bulk-input-card"><div className="panel-heading"><div className="feature-icon"><Icon name="list"/></div><span className="tag">{ui.bulkDetails.batchTag}</span></div><h2>{ui.bulk.title}</h2><p className="muted">{ui.bulk.help}</p><form onSubmit={run}><label htmlFor={id}>{ui.bulk.label}</label><textarea id={id} value={text} onChange={e=>{setText(e.target.value);setResults(null);setError("");setFileName("");}} rows={7} placeholder={ui.bulk.placeholder} maxLength={MAX_CSV_BYTES} spellCheck={false} aria-describedby={id+"-help"} aria-invalid={!!error}/><p id={id+"-help"} className="fine-print">{ui.bulk.csvHelp}</p><div className="bulk-actions"><div className="button-row"><button type="button" className="button" onClick={()=>fileInput.current?.click()}><Icon name="upload" size={17}/>{ui.bulk.upload}</button><input ref={fileInput} type="file" accept=".csv,text/csv" hidden onChange={upload} aria-label={ui.bulk.upload}/>{text&&<button type="button" className="text-button" onClick={()=>{setText("");setResults(null);setError("");setFileName("");}}>{ui.bulk.clear}</button>}</div><button className="button primary" type="submit">{ui.bulk.submit}<Icon name="arrow" size={17}/></button></div>{fileName&&<p className="fine-print"><Icon name="file" size={14}/> {fileName}</p>}{error&&<p role="alert" className="alert error-alert">{error}</p>}</form><p className="privacy-caption"><Icon name="lock" size={14}/>{ui.bulk.privacy}</p></section>{results&&<section className="bulk-results" aria-labelledby="bulk-result-title"><div className="result-title"><div><span className="eyebrow">{ui.bulkDetails.complete}</span><h2 id="bulk-result-title">{ui.bulk.results}</h2></div><button className="button" onClick={download}><Icon name="download" size={16}/>{ui.bulk.export}</button></div><div className="batch-stats" role="status"><div><strong>{results.length}</strong><span>{ui.bulk.total}</span></div><div className="success-text"><strong>{results.filter(r=>r.valid).length}</strong><span>{ui.bulk.valid}</span></div><div className="error-text"><strong>{results.filter(r=>!r.valid).length}</strong><span>{ui.bulk.invalid}</span></div></div><div className="table-scroll" role="region" aria-label={ui.bulk.results} tabIndex={0}><table className="data-table"><thead><tr>{[ui.bulk.iban,ui.bulk.country,ui.bulk.status,ui.bulk.bank,ui.bulk.bic,ui.bulk.error].map(v=><th key={v} scope="col">{v}</th>)}</tr></thead><tbody>{results.map(r=>localizeResult(r,locale)).map((r,i)=><tr key={i}><td><code>{r.formatted||"—"}</code></td><td>{r.country?.name||"—"}</td><td><span className={`tag ${r.valid?"tag-green":"tag-red"}`}>{r.valid?ui.bulk.valid:ui.bulk.invalid}</span></td><td>{r.bank?.name||ui.scanner.unavailable}</td><td><code>{r.bank?.bic||"—"}</code></td><td>{r.valid?ui.bulkDetails.checksPassed:r.errors.join(" ")}</td></tr>)}</tbody></table></div><div className="trust-note"><Icon name="shield"/><p>{ui.scanner.disclaimer}</p></div></section>}</div>;
}
