"use client";
import Link from "next/link";
import { useId, useState } from "react";
import { countries, getCountry } from "@/lib/countries";
import { analyzeIban, formatIban, generateIban, normalizeIban } from "@/lib/iban";
import { searchBanks, type BankRecord } from "@/lib/banks";
import { isBicFormat } from "@/lib/bic";
import { Icon } from "./icon";
import { CopyButton } from "./copy-button";
import { ScanResult } from "./scan-result";
import { formatMessage } from "@/locales/ui.en";
import { useUi, useLocale } from "./locale-provider";
import { BankProfile } from "./bank-profile";
import { countryName } from "@/lib/iban-display";
export function Formatter(){
  const ui = useUi();
  const [value,setValue]=useState("");const id=useId();return <section className="card utility-card"><span className="feature-icon"><Icon name="text"/></span><p className="muted">{ui.tools.formatterText}</p><label htmlFor={id}>{ui.tools.formatterLabel}</label><input id={id} value={value} onChange={e=>setValue(e.target.value)} maxLength={256} placeholder={ui.scanner.placeholder} spellCheck={false} autoComplete="off"/>{value.trim()&&<div className="format-results">{[[ui.tools.electronic,normalizeIban(value)],[ui.tools.print,formatIban(value)]].map(([label,v])=><div key={label}><span>{label}</span><div><code>{v}</code><CopyButton value={v}/></div></div>)}<p className="fine-print">{analyzeIban(value).valid?ui.scanner.success:ui.scanner.failure}. <Link href="/tools/iban-validator" className="text-link">{ui.utility.openValidator} <Icon name="arrow" size={13}/></Link></p></div>}</section>}
export function Generator(){
  const ui = useUi();
  const { locale } = useLocale();const id=useId();const [country,setCountry]=useState("IT");const [bban,setBban]=useState("");const [iban,setIban]=useState("");const [error,setError]=useState("");const selected=getCountry(country)!;function submit(e:React.FormEvent){e.preventDefault();try{setIban(generateIban(country,bban));setError("");}catch(e){setError(locale==="en"&&e instanceof Error?e.message:ui.utility.calculationError+" "+formatMessage(ui.utility.bbanPlaceholder,{length:selected.length-4,format:selected.format}));setIban("");}}return <div><section className="card utility-card"><span className="feature-icon"><Icon name="code"/></span><p className="muted">{ui.tools.generatorHelp}</p><form onSubmit={submit}><label htmlFor={id+"-country"}>{ui.tools.generatorLabel}</label><select id={id+"-country"} value={country} onChange={e=>{setCountry(e.target.value);setIban("");setError("");}}>{countries.map(c=><option key={c.code} value={c.code}>{countryName(c.code,locale,c.name)} ({c.code})</option>)}</select><label htmlFor={id+"-bban"}>{ui.tools.bbanLabel}</label><input id={id+"-bban"} value={bban} onChange={e=>{setBban(normalizeIban(e.target.value));setIban("");setError("");}} required maxLength={256} placeholder={formatMessage(ui.utility.bbanPlaceholder,{length:selected.length-4,format:selected.format})} spellCheck={false} autoComplete="off" aria-describedby={id+"-help"}/><p id={id+"-help"} className="fine-print">{formatMessage(ui.utility.bbanDescription,{country:countryName(selected.code,locale,selected.name),length:selected.length-4,notes:locale==="en"?selected.notes:""})}</p><button className="button primary" type="submit">{ui.tools.generatorSubmit}<Icon name="arrow" size={17}/></button>{error&&<p className="alert error-alert" role="alert">{error}</p>}</form></section>{iban&&<><p className="alert"><Icon name="info" size={17}/>{ui.utility.calculationNotice}</p><ScanResult result={analyzeIban(iban)} showAi={false}/></>}</div>}
export function CountryChecker(){
  const ui = useUi();
  const { locale } = useLocale();const id=useId();const [input,setInput]=useState("");const c=getCountry(normalizeIban(input).slice(0,2));return <section className="card utility-card"><span className="feature-icon"><Icon name="globe"/></span><p className="muted">{ui.tools.countryHelp}</p><label htmlFor={id}>{ui.tools.countryLabel}</label><input id={id} value={input} onChange={e=>setInput(e.target.value)} placeholder={ui.utility.countryPlaceholder} maxLength={256} autoComplete="off" spellCheck={false}/>{input.trim().length>=2&&(c?<div className="country-check-result"><span className="country-result-flag">{c.flag}</span><h2>{countryName(c.code,locale,c.name)}</h2><dl className="detail-list"><div><dt>{ui.utility.countryCode}</dt><dd>{c.code}</dd></div><div><dt>{ui.scanner.length}</dt><dd>{c.length} {ui.common.characters}</dd></div><div><dt>{ui.utility.bbanStructure}</dt><dd><code>{c.format}</code></dd></div><div><dt>{ui.scanner.sepa}</dt><dd>{c.sepa?ui.scanner.sepaYes:ui.scanner.sepaNo}</dd></div></dl><p className="fine-print">{ui.tools.countryScope}</p><Link className="text-link" href={`/iban/${c.slug}`}>{formatMessage(ui.utility.countryFormatLink,{country:countryName(c.code,locale,c.name)})} <Icon name="arrow" size={15}/></Link></div>:<p role="status" className="alert error-alert">{ui.tools.noCountry}</p>)}</section>}
export function BankFinder(){
  const ui = useUi();
  const id=useId();const [q,setQ]=useState("");const [results,setResults]=useState<BankRecord[]|null>(null);const [bic,setBic]=useState("");const [error,setError]=useState("");const bicValid=isBicFormat(bic);function search(e:React.FormEvent){e.preventDefault();if(q.trim().length<2){setError(ui.tools.bankEmpty);return;}setError("");setResults(searchBanks(q));}return <div className="grid-2 banking-tools"><section className="card utility-card"><span className="feature-icon"><Icon name="building"/></span><p className="muted">{ui.tools.bankHelp}</p><form onSubmit={search}><label htmlFor={id+"-bank"}>{ui.tools.bankQuery}</label><input id={id+"-bank"} value={q} onChange={e=>{setQ(e.target.value);setResults(null);setError("");}} maxLength={100} placeholder={ui.utility.bankPlaceholder}/><button type="submit" className="button primary">{ui.tools.bankSearch}<Icon name="arrow" size={16}/></button></form>{error&&<p role="alert" className="field-error">{error}</p>}{results&&<div className="bank-search-results" aria-live="polite">{results.length?results.map(r=><article key={r.bic}><BankProfile bank={r}/><p className="mono">{r.bic}<CopyButton value={r.bic}/></p><p className="fine-print">{r.countryCode} · {r.bankIdentifier} · {ui.utility.verified} {r.verifiedAt}</p><a className="text-link" href={r.source} target="_blank" rel="noopener noreferrer">{ui.utility.bankSource} <Icon name="external" size={12}/></a></article>):<p className="alert">{ui.tools.noBank}</p>}</div>}</section><section className="card utility-card"><span className="feature-icon"><Icon name="scan"/></span><h2>{ui.tools.bicSyntax}</h2><label htmlFor={id+"-bic"}>{ui.tools.bicLabel}</label><input id={id+"-bic"} value={bic} onChange={e=>setBic(normalizeIban(e.target.value))} maxLength={30} placeholder={ui.utility.bicPlaceholder} spellCheck={false}/>{bic&&<p role="status" className={`alert ${bicValid?"success-alert":"error-alert"}`}>{bicValid?ui.tools.bicValid:ui.tools.bicInvalid}</p>}<p className="fine-print">{ui.utility.bicNotice}</p></section></div>}
