/** English is the complete source locale. New translations inherit missing keys. */
const en = {
  navigation: { tools: "Tools", countries: "Countries", api: "API", resources: "Resources", ai: "AI", scan: "Scan IBAN" },
  common: { home: "Home", countries: "Countries", resources: "Resources", readGuide: "Read guide", exploreTools: "Explore tools", scanIban: "Scan an IBAN", source: "Sources & methodology", formatGuide: "Explore the IBAN format", overview: "Banking overview", exampleOnly: "Published format example. Do not use it to make a payment.", unavailable: "Unavailable", characters: "characters", yes: "Yes", no: "No", learnMore: "Learn more", updated: "Reviewed 20 September 2026" },
  country: { eyebrow: "Country directory", title: "Local formats. Global understanding.", intro: "Explore supported IBAN formats, local bank identifiers and SEPA geographical coverage. Every country has its own structure; a valid format never proves an account is active.", scope: "SEPA geographical scope", currency: "Country currency", prefix: "IBAN prefix", length: "IBAN length", format: "National format", interpretation: "How to interpret these details", next: "Before making a transfer", boundaries: "What these checks can tell you", sources: "Format definitions follow the SWIFT IBAN Registry. SEPA scope follows the European Payments Council. Currency describes the country context, not the currency of a specific account.", directory: "Browse all countries", noBank: "A bank identifier is a code extracted from the IBAN. A bank name or BIC needs a separate, reliable directory match. If that match is unavailable, IBANScan says so.", scopeNote: "Geographical inclusion is not a guarantee that a particular bank participates in every SEPA scheme or that a payment will be accepted.", notScopeNote: "This country is not marked as being within SEPA geographical scope in the bundled data. An IBAN alone does not determine which international payment services are available.", confirm: "Confirm payment instructions with the intended recipient through a trusted channel. Your payment provider determines routing, supported currencies, fees and any recipient checks.", limitations: "IBANScan checks IBAN structure and available banking data. It does not confirm account ownership, account balance, or whether an account is currently active." },
  iban: { eyebrow: "IBAN format reference", layout: "Read the structure", columnPart: "Component", columnPosition: "Positions", columnLength: "Length", columnExample: "Example", code: "Country code", checks: "International check digits", bban: "BBAN (national account format)", bank: "Bank identifier", branch: "Branch identifier", account: "Account identifier", positions: "Positions count from 1 in the unspaced IBAN. Identifier rows are contained within the BBAN; other BBAN characters may be domestic check digits or reserved fields.", validation: "How validation works", rules: ["Remove spaces and convert letters to uppercase; retain punctuation as an input error.", "Match the country prefix and exact registered length.", "Check each BBAN character against the national numeric and alphabetic pattern.", "Move the first four characters to the end, convert letters to numbers (A = 10 through Z = 35), and compute MOD-97. The remainder must be 1.", "Extract identifiers only from the published country layout. Resolve bank names and BICs separately when a reliable dataset is available."], caution: "The international checksum detects many typing errors. Domestic account checks, bank assignment, ownership and account status require separate verification.", notation: "In the format notation, n means a digit, a means a letter and c means a letter or digit. A number before ! specifies the exact number of characters.", mistakes: "Common mistakes to avoid", mistakesList: ["Keep leading zeros: they are part of the account format.", "Do not replace a letter with a similar-looking digit, such as O with 0.", "Do not repair an invalid IBAN by recalculating check digits unless you are testing software. Request the correct payment details from the source.", "Use a bank-provided IBAN for real payments. A generated, checksum-valid number is not a newly opened account."] },
  resources: { eyebrow: "The IBANScan library", title: "A little clarity goes a long way.", intro: "Practical guides to the identifiers behind your payments. Understand what a check proves, what a bank code means and where the limits are.", further: "Continue exploring", sources: "Authoritative references", disclaimer: "Educational information about payment identifiers. Use your payment provider for account confirmation and payment instructions." },
  legal: { status: "Publication notice", notice: "These pages describe this application's default configuration. The operator must add its legal identity, contact details, applicable jurisdiction, hosting details and any enabled providers before public launch. These are draft notices, not a claim of legal compliance.", contact: "Contact details have not been configured for this deployment. For questions about a bank account, payment or suspected fraud, contact your bank using its official channels." },
} as const;

export default en;
