import type { Ui } from "./types";
import type { Messages, Locale } from "@/lib/i18n";

const words = {
  it: {
    home: "Home", read: "Leggi la guida", sources: "Fonti e metodologia", format: "Esplora il formato IBAN", overview: "Panoramica bancaria", example: "Esempio pubblico di formato. Non usarlo per effettuare pagamenti.", yes: "Sì", no: "No", more: "Scopri di più", updated: "Revisionato il 22 settembre 2026", prefix: "Prefisso IBAN", national: "Formato nazionale", interpretation: "Come interpretare i dati", next: "Prima di un bonifico", boundaries: "Cosa indicano questi controlli", reference: "I formati seguono il registro IBAN di SWIFT e l’area SEPA segue lo European Payments Council. La valuta descrive il paese, non il singolo conto.", confirm: "Conferma le istruzioni con il destinatario attraverso un canale affidabile. Il fornitore di pagamento stabilisce instradamento, valute, commissioni e verifiche del beneficiario.", layout: "Leggere la struttura", part: "Componente", positions: "Posizioni", length: "Lunghezza", sample: "Esempio", positionNote: "Le posizioni partono da 1 nell’IBAN senza spazi. Gli identificativi sono inclusi nel BBAN; gli altri caratteri possono essere controlli nazionali o campi riservati.", validation: "Come funziona la verifica", rules: ["Rimuovi gli spazi e converti le lettere in maiuscolo. La punteggiatura resta un errore.", "Controlla il prefisso, la lunghezza e il formato nazionale BBAN.", "Sposta i primi quattro caratteri in fondo e converti le lettere in numeri (A = 10, Z = 35). Il resto MOD-97 deve essere 1.", "Nome della banca e BIC richiedono una fonte affidabile separata."], notation: "n indica una cifra, a una lettera, c una lettera o una cifra. Il numero prima di ! indica la lunghezza esatta.", mistakes: "Errori da evitare", mistakesList: ["Conserva gli zeri iniziali.", "Non scambiare O con 0 o altre lettere con cifre simili.", "Non ricalcolare il checksum per correggere dati di pagamento. Richiedi l’IBAN corretto alla fonte.", "Un IBAN calcolato non crea un conto. Per pagamenti reali usa i dati forniti dalla banca."], library: "La biblioteca di IBANScan", libraryTitle: "Un po’ di chiarezza fa la differenza.", libraryIntro: "Guide pratiche agli identificativi dei pagamenti: significato, controlli e limiti.", education: "Informazioni educative sugli identificativi di pagamento. Per confermare un conto e le istruzioni di pagamento, rivolgiti al tuo fornitore.", publication: "Avviso di pubblicazione", notice: "Queste pagine descrivono la configurazione predefinita. Prima della pubblicazione il gestore deve inserire identità legale, contatti, giurisdizione, hosting e fornitori attivi. Sono bozze, non dichiarazioni di conformità legale.", contact: "I contatti del gestore non sono configurati. Per domande su conti, pagamenti o frodi, contatta la banca tramite i canali ufficiali.",
  },
  de: {
    home: "Startseite", read: "Ratgeber lesen", sources: "Quellen und Methodik", format: "IBAN-Format entdecken", overview: "Bankübersicht", example: "Veröffentlichtes Formatbeispiel. Nicht für Zahlungen verwenden.", yes: "Ja", no: "Nein", more: "Mehr erfahren", updated: "Geprüft am 22. September 2026", prefix: "IBAN-Präfix", national: "Nationales Format", interpretation: "Diese Angaben verstehen", next: "Vor einer Überweisung", boundaries: "Was diese Prüfungen aussagen", reference: "Die Formate folgen dem SWIFT-IBAN-Register und der SEPA-Geltungsbereich dem European Payments Council. Die Währung beschreibt das Land, nicht das einzelne Konto.", confirm: "Bestätigen Sie Zahlungsanweisungen über einen vertrauenswürdigen Kanal beim Empfänger. Ihr Zahlungsdienstleister bestimmt Weiterleitung, Währungen, Gebühren und Empfängerprüfungen.", layout: "Die Struktur lesen", part: "Bestandteil", positions: "Positionen", length: "Länge", sample: "Beispiel", positionNote: "Positionen zählen ab 1 in der IBAN ohne Leerzeichen. Kennungen liegen in der BBAN; weitere Zeichen können nationale Prüfziffern oder reservierte Felder sein.", validation: "So funktioniert die Prüfung", rules: ["Leerzeichen entfernen und Buchstaben großschreiben. Satzzeichen bleiben Eingabefehler.", "Präfix, Länge und nationales BBAN-Muster prüfen.", "Die ersten vier Zeichen ans Ende stellen, Buchstaben in Zahlen umwandeln (A = 10, Z = 35). Der MOD-97-Rest muss 1 sein.", "Bankname und BIC benötigen eine gesonderte verlässliche Quelle."], notation: "n steht für Ziffer, a für Buchstabe, c für Buchstabe oder Ziffer. Die Zahl vor ! gibt die exakte Länge an.", mistakes: "Häufige Fehler vermeiden", mistakesList: ["Führende Nullen beibehalten.", "O und 0 oder ähnliche Buchstaben und Zahlen nicht vertauschen.", "Zahlungsangaben nicht durch Neuberechnung der Prüfziffern reparieren. Richtige Angaben bei der Quelle anfordern.", "Eine berechnete IBAN eröffnet kein Konto. Für echte Zahlungen die Bankangaben verwenden."], library: "Die IBANScan-Bibliothek", libraryTitle: "Ein wenig Klarheit macht viel aus.", libraryIntro: "Praktische Ratgeber zu Zahlungskennungen: Bedeutung, Prüfungen und Grenzen.", education: "Lerninhalte zu Zahlungskennungen. Kontobestätigungen und Zahlungsanweisungen erhalten Sie bei Ihrem Zahlungsdienstleister.", publication: "Veröffentlichungshinweis", notice: "Diese Seiten beschreiben die Standardkonfiguration. Vor der Veröffentlichung muss der Betreiber rechtliche Identität, Kontakt, Rechtsordnung, Hosting und aktive Anbieter ergänzen. Es sind Entwürfe, keine Zusicherung rechtlicher Konformität.", contact: "Betreiber-Kontaktdaten sind nicht konfiguriert. Bei Fragen zu Konten, Zahlungen oder Betrug wenden Sie sich über offizielle Kanäle an Ihre Bank.",
  },
  fr: {
    home: "Accueil", read: "Lire le guide", sources: "Sources et méthodologie", format: "Explorer le format IBAN", overview: "Aperçu bancaire", example: "Exemple de format publié. Ne pas utiliser pour un paiement.", yes: "Oui", no: "Non", more: "En savoir plus", updated: "Révisé le 22 septembre 2026", prefix: "Préfixe IBAN", national: "Format national", interpretation: "Interpréter ces données", next: "Avant un virement", boundaries: "Ce que ces contrôles indiquent", reference: "Les formats suivent le registre IBAN de SWIFT et le périmètre SEPA suit le Conseil européen des paiements. La devise décrit le pays, pas un compte particulier.", confirm: "Confirmez les instructions auprès du destinataire par un canal de confiance. Votre prestataire détermine l’acheminement, les devises, les frais et les contrôles du bénéficiaire.", layout: "Lire la structure", part: "Composant", positions: "Positions", length: "Longueur", sample: "Exemple", positionNote: "Les positions commencent à 1 dans l’IBAN sans espaces. Les identifiants font partie du BBAN ; les autres caractères peuvent être des contrôles nationaux ou des champs réservés.", validation: "Comment fonctionne la validation", rules: ["Supprimer les espaces et convertir les lettres en majuscules. La ponctuation reste une erreur.", "Vérifier le préfixe, la longueur et le modèle BBAN national.", "Déplacer les quatre premiers caractères à la fin, convertir les lettres en nombres (A = 10, Z = 35). Le reste MOD-97 doit être 1.", "Le nom de la banque et le BIC nécessitent une source fiable distincte."], notation: "n est un chiffre, a une lettre et c une lettre ou un chiffre. Le nombre devant ! donne la longueur exacte.", mistakes: "Erreurs à éviter", mistakesList: ["Conserver les zéros initiaux.", "Ne pas confondre O et 0 ou d’autres caractères similaires.", "Ne pas réparer des coordonnées de paiement en recalculant la clé. Demander les bonnes coordonnées à la source.", "Un IBAN calculé ne crée pas de compte. Utiliser les coordonnées de la banque pour les paiements réels."], library: "La bibliothèque IBANScan", libraryTitle: "Un peu de clarté change tout.", libraryIntro: "Des guides pratiques sur les identifiants de paiement : signification, vérifications et limites.", education: "Informations éducatives sur les identifiants de paiement. Consultez votre prestataire pour confirmer un compte ou des instructions de paiement.", publication: "Avis de publication", notice: "Ces pages décrivent la configuration par défaut. Avant publication, l’opérateur doit compléter son identité juridique, ses contacts, la juridiction, l’hébergement et les fournisseurs actifs. Ce sont des projets, pas une déclaration de conformité juridique.", contact: "Les coordonnées de l’opérateur ne sont pas configurées. Pour les comptes, paiements ou fraudes, contactez votre banque par ses canaux officiels.",
  },
  es: {
    home: "Inicio", read: "Leer guía", sources: "Fuentes y metodología", format: "Explorar formato IBAN", overview: "Panorama bancario", example: "Ejemplo de formato publicado. No lo utilices para realizar pagos.", yes: "Sí", no: "No", more: "Más información", updated: "Revisado el 22 de septiembre de 2026", prefix: "Prefijo IBAN", national: "Formato nacional", interpretation: "Cómo interpretar los datos", next: "Antes de una transferencia", boundaries: "Qué indican estas comprobaciones", reference: "Los formatos siguen el registro IBAN de SWIFT y el ámbito SEPA sigue al Consejo Europeo de Pagos. La moneda describe el país, no una cuenta concreta.", confirm: "Confirma las instrucciones con el destinatario por un canal de confianza. Tu proveedor determina el enrutamiento, las monedas, las comisiones y las comprobaciones del beneficiario.", layout: "Leer la estructura", part: "Componente", positions: "Posiciones", length: "Longitud", sample: "Ejemplo", positionNote: "Las posiciones empiezan en 1 en el IBAN sin espacios. Los identificadores están dentro del BBAN; otros caracteres pueden ser controles nacionales o campos reservados.", validation: "Cómo funciona la validación", rules: ["Elimina espacios y convierte las letras a mayúsculas. La puntuación sigue siendo un error.", "Comprueba el prefijo, la longitud y el patrón BBAN nacional.", "Mueve los primeros cuatro caracteres al final, convierte las letras en números (A = 10, Z = 35). El resto MOD-97 debe ser 1.", "El nombre del banco y el BIC requieren una fuente fiable independiente."], notation: "n es un dígito, a una letra y c una letra o dígito. El número antes de ! indica la longitud exacta.", mistakes: "Errores que debes evitar", mistakesList: ["Conserva los ceros iniciales.", "No confundas O y 0 ni otros caracteres similares.", "No repares datos de pago recalculando los controles. Solicita los datos correctos a la fuente.", "Un IBAN calculado no crea una cuenta. Usa los datos bancarios oficiales para pagos reales."], library: "La biblioteca de IBANScan", libraryTitle: "Un poco de claridad marca la diferencia.", libraryIntro: "Guías prácticas sobre identificadores de pago: significado, comprobaciones y límites.", education: "Información educativa sobre identificadores de pago. Consulta a tu proveedor para confirmar cuentas e instrucciones de pago.", publication: "Aviso de publicación", notice: "Estas páginas describen la configuración predeterminada. Antes de publicar, el operador debe añadir identidad legal, contacto, jurisdicción, alojamiento y proveedores activos. Son borradores, no una declaración de cumplimiento jurídico.", contact: "No se han configurado los contactos del operador. Para cuentas, pagos o fraude, contacta con tu banco por sus canales oficiales.",
  },
};

export function referenceMessages(locale: Exclude<Locale, "en">, ui: Ui): Messages {
  const t = words[locale];
  return {
    navigation: ui.nav,
    common: { home: t.home, countries: ui.nav.countries, resources: ui.nav.resources, readGuide: t.read, exploreTools: ui.hero.explore, scanIban: ui.scanner.submit, source: t.sources, formatGuide: t.format, overview: t.overview, exampleOnly: t.example, unavailable: ui.scanner.notAvailable, characters: ui.common.characters, yes: t.yes, no: t.no, learnMore: t.more, updated: t.updated },
    country: { eyebrow: ui.nav.countries, title: ui.home.countryTitle, intro: ui.home.countryDescription, scope: ui.scanner.sepa, currency: ui.scanner.currency, prefix: t.prefix, length: ui.scanner.length, format: t.national, interpretation: t.interpretation, next: t.next, boundaries: t.boundaries, sources: t.reference, directory: ui.home.countryCta, noBank: ui.tools.bankHelp, scopeNote: ui.tools.countryScope, notScopeNote: ui.scanner.sepaNo + ". " + ui.scanner.sepaNote, confirm: t.confirm, limitations: ui.scanner.disclaimer },
    iban: { eyebrow: t.format, layout: t.layout, columnPart: t.part, columnPosition: t.positions, columnLength: t.length, columnExample: t.sample, code: ui.utility.countryCode, checks: ui.homeDetails.checkDigits, bban: "BBAN", bank: ui.scanner.bankId, branch: ui.scanner.branch, account: ui.scanner.account, positions: t.positionNote, validation: t.validation, rules: t.rules, caution: ui.scanner.domestic, notation: t.notation, mistakes: t.mistakes, mistakesList: t.mistakesList },
    resources: { eyebrow: t.library, title: t.libraryTitle, intro: t.libraryIntro, further: ui.tools.related, sources: t.sources, disclaimer: t.education },
    legal: { status: t.publication, notice: t.notice, contact: t.contact },
  };
}
