export const ui = {
  brand: "IBANScan",
  shell: { homeLabel: "IBANScan home", mainNavigation: "Main navigation", mobileNavigation: "Mobile navigation", skip: "Skip to content", noScript: "Enable JavaScript to use the private IBAN tools. Guides and country information remain available without it.", loadingLabel: "Loading page", loading: "Loading…", advertisement: "Advertisement" },
  bulkDetails: { batchTag: "100 IBANs / batch", complete: "BATCH COMPLETE", checksPassed: "All structural checks passed" },
  footerLinks: { validator: "IBAN Validator", analyzer: "IBAN Analyzer", bic: "BIC / SWIFT Finder", bulk: "Bulk Validator", apiDocs: "API documentation" },
  toolsPage: { metadataTitle: "IBAN & Banking Tools", metadataDescription: "Explore free IBAN validation, analysis, formatting, BBAN-to-IBAN calculation, sourced BIC lookup, SEPA checks and bulk CSV validation.", playgroundTitle: "API Playground", playgroundDescription: "Test a real authenticated API request." },
  toolPage: {
    breadcrumb: "TOOLS", aboutTitle: "What this tool tells you", resultScope: "Results describe mathematical validation and available reference data. They cannot confirm the account holder, balance or whether an account is active.", scannerScope: "Whitespace is removed and lowercase letters are converted automatically. We check the registered country, exact length, BBAN structure and international MOD-97 checksum. Domestic account check algorithms are outside this check. Correct details with the account’s issuing bank.",
    sourceIntro: "Country rules are sourced from the", sourceLabel: "SWIFT IBAN registry", sourceScope: ". SEPA coverage describes geography; institution participation must be verified separately.", guideLink: "Learn about IBAN validation",
  },
  common: { characters: "characters", closeDialog: "Close dialog", copyField: "Copy {label}" },
  bankDetails: { title: "Verified bank profile", website: "Official website", contact: "Contact the bank", phone: "Telephone", headquarters: "Headquarters", registeredOffice: "Registered office", addressUnavailable: "Headquarters address unavailable", unavailable: "No verified bank profile is available for this identifier.", source: "Source", reviewed: "Reviewed", scope: "These are the bank’s public contact details, not the address of the account holder or branch." },
  result: { eyebrow: "IBAN ANALYSIS", accessibleLabel: "Validation result", checksumPassed: "MOD-97 passed", checkRequired: "Check required" },
  scannerDetails: { italianOnly: "Enter an Italian IBAN beginning with IT to extract ABI and CAB codes.", oversized: "Enter one IBAN using no more than 256 input characters." },
  utility: {
    openValidator: "Open validator", calculationError: "Unable to calculate IBAN.", bbanPlaceholder: "{length} characters · {format}", bbanDescription: "{country}: {length} BBAN characters. {notes}", calculationNotice: "Calculated from the supplied BBAN. Confirm this result with the issuing bank before using it.",
    countryPlaceholder: "e.g. IT", countryCode: "Country code", bbanStructure: "BBAN structure", countryFormatLink: "Explore {country}’s IBAN format", bankPlaceholder: "e.g. ABNA or NatWest", verified: "Verified", bankSource: "Bank source", bicPlaceholder: "e.g. ABNANL2A", bicNotice: "A matching format is not a directory lookup. Confirm a BIC directly with the receiving bank.",
  },
  playgroundDetails: { keyPlaceholder: "Your private API key", validateOption: "POST /api/v1/iban/validate", analyzeOption: "POST /api/v1/iban/analyze", keyRedaction: "<your-key>" },
  aiPage: { metadataTitle: "IBANScan AI — Understand Your IBAN", metadataDescription: "Get AI-assisted explanations grounded in real IBAN validation results, with verified, calculated and unavailable information clearly distinguished.", eyebrow: "IBANSCAN AI" },
  resultsPage: { metadataTitle: "IBAN Scan Result", eyebrow: "PRIVATE IBAN ANALYSIS", title: "A closer look at your IBAN.", description: "Review the format, check digits and available banking information." },
  homeDetails: {
    metadataTitle: "IBAN Validator & Banking Tools", metadataDescription: "Scan, verify and understand IBANs. Private browser-based validation for 89 country formats, sourced bank information, bulk CSV tools and AI explanations.",
    standardNote: "Built on the international IBAN standard", verifyLink: "Know exactly what we verify", factsLabel: "Platform facts", zero: "Zero", free: "Free", promiseLink: "Our promise", explained: "EXPLAINED", checkDigits: "Check digits", domesticFormat: "Domestic account format", codeComment: "// Clear inputs. Useful answers.\n", codeCaption: "Illustrative response excerpt · authenticated API", faqDescription: "Clarity starts with knowing the limits.",
    faqs: [
      { q: "What does IBANScan actually verify?", a: "We check the country’s registered IBAN format, exact length, domestic structure and international MOD-97 check digits. Where a verified source supports it, we also show the bank name and BIC. A valid result does not confirm account ownership, available funds or whether the account is active." },
      { q: "Is my IBAN stored or shared?", a: "Standard scans, formatting and bulk validation run in your browser. We do not send or store these IBANs. AI is optional: with your consent, the server analyzes your IBAN and sends only redacted facts and your question to the configured provider. Result links require a separate confirmation before including an IBAN." },
      { q: "Why might bank information be unavailable?", a: "An IBAN’s structure can often reveal a bank identifier, but a current bank name or BIC needs a reliable directory. Our verified dataset is intentionally small. If there is no source-backed match, we say so rather than guess." },
      { q: "Does a valid IBAN mean a payment will go through?", a: "No. The account may be closed, restricted or unable to receive the payment. The beneficiary name and bank’s payment-scheme participation also require separate checks. Always confirm payment details directly through a trusted channel." },
      { q: "Can I validate more than one IBAN?", a: "Yes. The free bulk validator checks up to 100 entries per batch. Paste a list or open a CSV on your device, inspect the result of each check and export a CSV report." },
    ],
  },
  nav: { tools: "Tools", countries: "Countries", api: "API", resources: "Resources", ai: "IBANScan AI", scan: "Scan IBAN", menu: "Open navigation", close: "Close navigation", theme: "Toggle color theme", language: "Page language" },
  hero: { badge: "A little clarity. For every IBAN.", title: "Scan. Verify.", accent: "Understand.", description: "Instantly analyze IBANs and get clear banking information, validation results and AI-powered explanations.", privacy: "Private by design", privacyDetail: "Basic scans stay in your browser. No sign-up. No storage.", example: "Try an example", explore: "Explore all tools" },
  scanner: { title: "IBAN scanner", label: "Enter an IBAN", placeholder: "e.g. IT60 X054 2811 1010 0000 0123 456", submit: "Scan IBAN", reset: "Clear", paste: "Paste IBAN", pasteError: "Clipboard access is unavailable. Paste directly into the input.", validation: "Validate & analyze", local: "Processed on your device", empty: "Enter an IBAN to continue.", detected: "detected", success: "Valid IBAN structure", failure: "Invalid IBAN", result: "Your scan, explained.", caption: "A clear breakdown of what we can verify.", copy: "Copy", copied: "Copied", copyError: "Unable to copy. Select and copy the text directly.", share: "Share result", shareTitle: "Create a private result link?", shareBody: "This link will contain the full IBAN after the # symbol. Anyone with the link can read it. It is not sent to our server, but it may remain in browser history or be read by browser extensions. Share only when you have permission.", shareConfirm: "Copy result link", cancel: "Cancel", checks: "Validation details", bankInfo: "Bank & account details", country: "Country", length: "IBAN length", bank: "Bank", bic: "BIC / SWIFT", bankId: "Bank identifier", branch: "Branch identifier", account: "Account identifier", bban: "BBAN", currency: "Country currency", unavailable: "Bank information unavailable", notAvailable: "Not available", sepa: "SEPA geographical scope", sepaYes: "Within SEPA scope", sepaNo: "Outside SEPA scope", sepaNote: "Country coverage does not confirm a bank’s participation or an account’s eligibility. SEPA transfers are in euro.", disclaimer: "IBANScan checks IBAN structure and available banking data. It does not confirm account ownership, account balance, or whether an account is currently active.", domestic: "Country format and international MOD-97 checksum are checked. Domestic account checks and bank participation are not verified.", source: "Verified source", invalidFields: "Extracted fields describe the entered structure. An invalid IBAN must be corrected before use." },
  home: {
    statCountries: "Country formats", statStandard: "International standard", statPrivacy: "Stored IBANs", statCost: "Free basic scans",
    processEyebrow: "FROM NUMBERS TO KNOWLEDGE", processTitle: "The details matter. We make them clear.", processDescription: "One scan brings the important pieces together, so you can spend less time checking and more time moving forward.",
    steps: [ { n: "01", title: "Paste an IBAN", text: "Spaces and lowercase letters? We handle them. Just bring the IBAN you want to check." }, { n: "02", title: "See the full picture", text: "Check the country format, length and checksum. See bank and branch identifiers where available." }, { n: "03", title: "Understand the result", text: "Get a plain-language explanation, with a clear line between calculated facts and unavailable information." } ],
    featuresEyebrow: "BUILT FOR CLARITY", featuresTitle: "Small details. Complete confidence in the check.", featuresDescription: "The right information, without the guesswork.",
    features: [ { icon: "scan", title: "More than a format check", text: "Country-specific structure, exact length and MOD-97 check digits. Every check, clearly explained." }, { icon: "building", title: "Bank data with a source", text: "Extract bank and branch identifiers. Bank names and BICs appear only when a verified source supports them." }, { icon: "globe", title: "A global perspective", text: "Explore national IBAN formats and SEPA geographical coverage from documented reference data." }, { icon: "sparkles", title: "Answers, in plain English", text: "Ask IBANScan AI to interpret the actual scan. No invented accounts, banks or ownership claims." } ],
    aiEyebrow: "MEET IBANSCAN AI", aiTitle: "Don’t just validate it. Understand it.", aiDescription: "Banking details can be technical. Your answers shouldn’t be. Ask a question about your scan and get an explanation grounded in its actual results.", aiCta: "Explore IBANScan AI", aiPreviewQuestion: "What do the numbers in an IBAN mean?", aiPreviewAnswer: "The first two letters identify the country. The next two digits are international check digits. The remaining characters follow that country’s domestic account format.", aiPreviewLabel: "Example explanation · calculated from the format", aiNote: "Available when an AI provider is configured. No account owner or balance information is available.",
    toolsEyebrow: "YOUR EVERYDAY TOOLKIT", toolsTitle: "One place. Every IBAN task.", toolsDescription: "From a quick check to a whole spreadsheet. Choose the tool for the job.", toolsCta: "View all tools",
    countryEyebrow: "LOCAL FORMATS. GLOBAL COVERAGE.", countryTitle: "Built to cross borders.", countryDescription: "Every country has its own format. Explore the details before you send.", countryCta: "Explore all countries",
    apiEyebrow: "FOR DEVELOPERS & BUSINESSES", apiTitle: "A smarter check in your workflow.", apiDescription: "Bring structured IBAN validation into your product. A straightforward API, predictable responses and no banking guesswork.", apiCta: "Read the API docs", apiSecondary: "Open playground",
    faqEyebrow: "GOOD QUESTIONS", faqTitle: "A few things worth knowing.", finalTitle: "Make sense of your next IBAN.", finalText: "A quick check. A clearer picture. Start right here.", finalCta: "Scan an IBAN" },
  tools: { eyebrow: "THE TOOLKIT", title: "Good tools. Clear answers.", description: "Practical banking utilities, built around your privacy. Pick a tool and get straight to it.", all: "All tools", related: "Keep exploring", faq: "About this tool", formatterLabel: "IBAN to format", formatterText: "Convert between readable groups of four and the electronic format. Formatting alone does not validate an IBAN.", electronic: "Electronic format", print: "Print format", generatorLabel: "Country", bbanLabel: "Domestic account number (BBAN)", generatorSubmit: "Calculate IBAN", generatorHelp: "Use a BBAN supplied by the bank. This tool calculates international check digits; it does not create an account, validate domestic check digits, or replace an IBAN issued by a bank.", generated: "Calculated IBAN", countryLabel: "Country code or IBAN", countryHelp: "Enter the first two letters of an IBAN to look up its national format.", noCountry: "This country format is not currently supported.", bankQuery: "Bank name, identifier or BIC", bankSearch: "Find bank", bankHelp: "Search only the source-backed directory bundled with this application. An empty result means we cannot verify a match.", noBank: "No verified bank information found. Check the details directly with the bank.", bankEmpty: "Enter at least two characters to search the verified directory.", bicLabel: "BIC / SWIFT code", bicSyntax: "BIC format check", bicValid: "This BIC matches the standard 8- or 11-character format. This does not confirm that it is assigned or active.", bicInvalid: "A BIC needs a 4-character alphanumeric business prefix, 2 country letters, a 2-character alphanumeric suffix, and an optional 3-character branch.", countryScope: "SEPA information refers to geographical scope. A participating country does not mean every bank or account supports a particular SEPA scheme." },
  bulk: { title: "More IBANs. The same clarity.", label: "Paste IBANs", placeholder: "One IBAN per line, or paste CSV data…", help: "Up to 100 entries per batch. CSV files up to 1 MB. Processed entirely in your browser.", upload: "Upload CSV", submit: "Validate batch", export: "Export CSV", clear: "Clear batch", results: "Batch results", valid: "Valid", invalid: "Invalid", total: "Total", fileError: "Choose a UTF-8 CSV file smaller than 1 MB.", empty: "Paste at least one IBAN or upload a CSV file.", limit: "This batch exceeds the free limit of 100 entries. Split the file into smaller batches.", privacy: "Your file is never uploaded. It stays on your device.", iban: "IBAN", country: "Country", status: "Status", bank: "Bank", bic: "BIC", error: "Details", csvHelp: "For multi-column CSVs, include an IBAN header. Single-column files also work. Comma, semicolon and tab separators are supported." },
  playground: { title: "Make your first request.", description: "Try the live API with your own key. Keys remain in this page’s memory and are sent only to this site’s API.", key: "API key", iban: "IBAN", endpoint: "Endpoint", submit: "Send request", loading: "Sending…", request: "Request", response: "Response", empty: "Your response will appear here.", error: "Unable to reach the API. Please try again.", help: "Ask your deployment administrator for an API key. An unconfigured API returns 503; invalid credentials return 401.", clear: "Clear credentials & response" },
  footer: { description: "A little clarity for every IBAN. Thoughtfully built banking tools, with privacy at their core.", tools: "Tools", explore: "Explore", company: "IBANScan", legal: "The details", about: "About", contact: "Contact", privacy: "Privacy", terms: "Terms", cookies: "Cookies", disclaimer: "Disclaimer", copyright: "IBANScan. Built for clarity.", note: "Structure validation, not account ownership verification." },
  error: { title: "Something interrupted this page.", description: "Please try again. Your IBAN has not been saved.", retry: "Try again", home: "Back to home", notFoundTitle: "This page is off the map.", notFoundText: "The page may have moved, but your next IBAN check is right here." },
} as const;

/** Named placeholders let translated sentences change word order safely. */
export function formatMessage(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => Object.hasOwn(values, key) ? String(values[key]) : match);
}
