/** Source-language editorial content. Keep prose here so locale editions can replace it as a unit. */
export type ContentSection = { heading: string; paragraphs: string[]; list?: string[] };
export type Guide = { slug: string; title: string; description: string; category: string; readTime: string; sections: ContentSection[]; faqs: { question: string; answer: string }[]; sources: { label: string; url: string }[]; tool: { label: string; href: string } };

export const sources = {
  swift: { label: "SWIFT — national IBAN formats and registry", url: "https://www.swift.com/fr/node/301396" },
  checksum: { label: "SWIFT — IBAN check digits and MOD-97", url: "https://www.swift.com/sites/default/files/documents/swift_solutions_faq_ibanplus.pdf" },
  bic: { label: "SWIFT — Business Identifier Code", url: "https://www.swift.com/standards/data-standards/bic-business-identifier-code" },
  sepa: { label: "European Payments Council — SEPA explained", url: "https://www.europeanpaymentscouncil.eu/about-sepa" },
  italy: { label: "Banca d’Italia — understanding an IBAN", url: "https://economiapertutti.bancaditalia.it/aree-tematiche/pagamenti/iban/" },
  germany: { label: "Deutsche Bundesbank — IBAN rules", url: "https://www.bundesbank.de/en/tasks/payment-systems/services/iban-rules" },
  france: { label: "Banque de France — RIB, IBAN and BIC", url: "https://www.banque-france.fr/en/node/2532" },
  spain: { label: "Banco de España — account number structure", url: "https://clientebancario.bde.es/pcb/en/blog/que-se-esconde-tras-los-numeros-de-tu-cuenta-corriente-.html" },
};

export const guides: Guide[] = [
  {
    slug: "what-is-an-iban", title: "What is an IBAN?", description: "Understand an International Bank Account Number, its country code, check digits and national account format — and what it cannot tell you.", category: "The essentials", readTime: "3 min read",
    sections: [
      { heading: "One identifier, a national structure", paragraphs: ["IBAN stands for International Bank Account Number. It presents account details in a standardized form for payment processing. Each registered country has a fixed layout, so a German IBAN and an Italian IBAN have different lengths even though both follow the same international framework.", "The first two characters identify the country format. Two international check digits follow. Everything after those four characters is the BBAN: the national part of the account identifier. SWIFT maintains the registry of national formats."] },
      { heading: "Reading and using an IBAN", paragraphs: ["Spaces group an IBAN for easier reading. They are not part of its electronic value. A formatter can remove those spaces and present a clean copy without changing the underlying identifier.", "Use the IBAN supplied by your bank or payment provider. When receiving payment instructions, compare the complete value with the original document. Treat unexpected changes in bank details as something to confirm independently before sending money."] },
      { heading: "What validation actually proves", paragraphs: ["A successful structural check says the characters fit the country format and the international checksum is consistent. It does not tell you whether a bank opened that account, who owns it or how much money it contains.", "A domestic bank code may be extractable from the national format. Translating that code into a bank name or BIC is a separate lookup that depends on a reliable directory. A missing lookup result does not by itself make the IBAN structurally invalid."] },
    ],
    faqs: [{ question: "Is an IBAN the same as an account number?", answer: "An IBAN is the international representation of account details. Its national portion may contain an account identifier, bank code, branch code and domestic check characters, depending on the country." }, { question: "Can IBANScan identify the account owner?", answer: "No. IBANScan does not identify an owner, check a balance or confirm that an account exists." }], sources: [sources.swift], tool: { label: "Try the IBAN analyzer", href: "/tools/iban-analyzer" },
  },
  {
    slug: "how-to-validate-an-iban", title: "How to validate an IBAN", description: "A practical guide to checking IBAN length, country structure and MOD-97 check digits, with clear next steps for invalid results.", category: "Validation", readTime: "4 min read",
    sections: [
      { heading: "Start with an exact copy", paragraphs: ["Copy the IBAN from the source without adding account names, labels or punctuation. Whitespace can be removed, and letters can be converted to uppercase. Other unexpected characters should trigger an error rather than being silently deleted.", "A validation result is most useful when it explains which check failed. An unsupported country, wrong length and incorrect checksum need different fixes."] },
      { heading: "The checks, in order", paragraphs: ["First identify a supported country code and compare the input with that country's registered length and BBAN pattern. Then validate the international check digits using MOD-97-10."], list: ["Move the first four characters to the end of the IBAN.", "Replace letters with values from A = 10 to Z = 35.", "Calculate the remainder on division by 97. A consistent IBAN produces a remainder of 1."] },
      { heading: "If the result is invalid", paragraphs: ["Compare the input with the bank-issued details, including leading zeros. Look for a missing character, a copied line break or a letter mistaken for a digit. If the value still fails, ask the source to provide it again.", "Do not use a generator to make an invalid payment instruction pass. Recalculating check digits can create a structurally consistent identifier that still points to the wrong account, or to no account at all."] },
      { heading: "Build a sensible validation workflow", paragraphs: ["For a form, check locally as a convenience and validate again on your server before processing submitted data. Distinguish a format warning from a payment-provider rejection. Keep raw account identifiers out of analytics and error logs.", "For a file, retain a row number alongside each result so errors can be traced back to the source without modifying the original data. Review rejected rows rather than dropping them silently."] },
    ],
    faqs: [{ question: "Can an IBAN pass MOD-97 but still be wrong?", answer: "Yes. A checksum-consistent string may have the wrong national structure, contain an unassigned bank identifier or refer to an account that does not exist. The checksum is one layer of validation." }, { question: "Does formatting change the checksum?", answer: "Display spaces and lowercase letters do not change a normalized IBAN. Changing, deleting or adding an actual letter or digit changes the identifier." }], sources: [sources.checksum, sources.swift], tool: { label: "Validate an IBAN", href: "/tools/iban-validator" },
  },
  {
    slug: "what-is-a-bic-swift-code", title: "What is a BIC / SWIFT code?", description: "Learn what an 8- or 11-character BIC identifies, how it differs from an IBAN and why bank-code lookups need verified reference data.", category: "Bank identifiers", readTime: "3 min read",
    sections: [
      { heading: "An identifier for a business party", paragraphs: ["BIC means Business Identifier Code. It is defined by ISO 9362 and often called a SWIFT code. It identifies a business party, rather than an individual customer account. BICs can identify financial and non-financial institutions.", "An eight-character BIC consists of a four-character business party prefix, a two-letter country code and a two-character suffix. Three optional characters identify a branch, location, department, service or unit."] },
      { heading: "A plausible code is not a verified code", paragraphs: ["A string can look like a BIC without corresponding to a current directory entry. A format check and a directory lookup answer different questions. SWIFT also distinguishes connected and non-connected BICs, so the mere presence of a BIC does not establish SWIFT network access.", "IBANScan only displays a resolved institution name or BIC when the configured banking source supplies that information. If a directory does not cover the code, the result remains unavailable."] },
      { heading: "Where to obtain payment instructions", paragraphs: ["Start with the recipient's bank-issued account details or your own payment provider's instructions. Whether a payment form asks for a BIC depends on the transfer route and the provider.", "Do not infer a BIC from a similar-looking bank name or reuse one found on an old invoice without checking the current instructions. A bank can use different identifiers for different purposes."] },
    ],
    faqs: [{ question: "Is a BIC an IBAN?", answer: "No. An IBAN represents account details in an international format; a BIC identifies a business party and may optionally identify a branch or unit." }, { question: "Can a BIC be calculated from an IBAN?", answer: "There is no universal calculation. In supported cases, an extracted national bank code can be matched to a reliable directory that supplies a BIC." }], sources: [sources.bic], tool: { label: "Open the BIC / SWIFT finder", href: "/tools/bic-swift-finder" },
  },
  {
    slug: "what-is-sepa", title: "What is SEPA?", description: "Understand the Single Euro Payments Area, geographical scope, bank participation and what an IBAN-based SEPA check can establish.", category: "Payments explained", readTime: "3 min read",
    sections: [
      { heading: "A common framework for euro payments", paragraphs: ["SEPA means Single Euro Payments Area. It provides a common framework for euro credit transfers and direct debits across its geographical scope. Its coverage extends beyond the European Union and beyond countries whose domestic currency is the euro.", "The European Payments Council publishes the scope and maintains payment schemes. Country inclusion, participation in a particular scheme and the handling of an individual payment are separate questions."] },
      { heading: "Three checks that should not be confused", paragraphs: ["An IBAN country prefix supports a country-level scope check. It does not answer every question needed to send a payment."], list: ["Geography: is the country within the published SEPA geographical scope?", "Participation: does the relevant payment service provider participate in the required scheme?", "Execution: do the account, currency, payment type and provider requirements allow this transfer?"] },
      { heading: "Understanding an IBANScan result", paragraphs: ["Our SEPA tool labels geographical eligibility using the country data bundled with the application. It does not query a bank's live participation or an account's capabilities.", "For example, a country can be inside SEPA geographical scope while using a national currency other than the euro. That does not mean a payment in the national currency is a SEPA euro transfer. Ask the payment provider about supported currencies and conversion.", "For timing, fees, transfer limits or whether instant payments are available, use the information supplied by the provider handling your payment."] },
    ],
    faqs: [{ question: "Is SEPA the same as the European Union?", answer: "No. SEPA geographical scope includes countries outside the European Union. It also differs from the euro area." }, { question: "Does a SEPA country result guarantee a transfer will work?", answer: "No. A geographical check does not verify scheme participation, account capabilities, currency support or acceptance of a specific payment." }], sources: [sources.sepa], tool: { label: "Check SEPA geographical scope", href: "/tools/sepa-checker" },
  },
  {
    slug: "how-italian-iban-works", title: "How does an Italian IBAN work?", description: "Read the 27-character Italian IBAN: IT prefix, international check digits, CIN, ABI, CAB and account field.", category: "Country guide", readTime: "3 min read",
    sections: [
      { heading: "The Italian layout", paragraphs: ["An Italian IBAN contains 27 characters. The IT prefix is followed by two international check digits. The national part begins with one alphabetic control character (CIN), then the five-digit ABI bank code, the five-digit CAB branch code and a twelve-character account field."], list: ["Positions 1–2: IT country prefix.", "Positions 3–4: international check digits.", "Position 5: domestic CIN character.", "Positions 6–10: ABI bank identifier.", "Positions 11–15: CAB branch identifier.", "Positions 16–27: account field."] },
      { heading: "Extracting is different from identifying", paragraphs: ["Reading an ABI or CAB from a correctly structured input is a deterministic operation. Naming a current bank or branch requires an authoritative mapping. Historical examples and remembered bank names are not enough to establish a current match.", "A missing bank lookup does not erase the extracted identifiers. IBANScan shows the calculated fields and the separate availability of bank information, allowing you to see what was checked."] },
      { heading: "When a result needs attention", paragraphs: ["Preserve every leading zero in the ABI, CAB and account field. Check that the fifth character is a letter and that the whole unspaced IBAN is 27 characters long.", "The Italian CIN and international check digits are separate control fields. A validator's international checksum result should not be interpreted as a claim that every bank-specific or domestic check has been performed. Refer to the displayed validation scope.", "A structurally correct Italian IBAN cannot establish the holder's identity. Verify recipient details through your payment provider and a trusted contact channel before acting on changed payment instructions."] },
    ],
    faqs: [{ question: "Where are ABI and CAB in an Italian IBAN?", answer: "In the unspaced IBAN, ABI occupies positions 6–10 and CAB occupies positions 11–15, counting the first character as position 1." }, { question: "Does IT mean the account is in euros?", answer: "IT identifies the Italian IBAN format. The IBAN itself does not reliably tell you the account's currency or balance." }], sources: [sources.italy, sources.swift], tool: { label: "Inspect an Italian IBAN", href: "/tools/abi-cab-checker" },
  },
  {
    slug: "how-to-find-abi-and-cab", title: "How to find ABI and CAB", description: "Locate the Italian bank and branch identifiers in an IBAN without confusing extracted codes with verified bank information.", category: "Bank identifiers", readTime: "3 min read",
    sections: [
      { heading: "Begin with the complete Italian IBAN", paragraphs: ["ABI and CAB are five-digit identifiers within the Italian IBAN's national part. ABI identifies the bank, while CAB identifies the branch. Use the complete bank-issued IBAN as your source rather than attempting to assemble one from partial details.", "After removing display spaces, count from the beginning of the IBAN: characters 6–10 are ABI and 11–15 are CAB. The leading IT, two international check digits and domestic CIN occupy the first five positions."] },
      { heading: "Keep the fields as text", paragraphs: ["A code such as 01234 is a five-character value. Converting it to a number removes a leading zero, which can make an exported field misleading. In spreadsheets, import bank identifiers as text and inspect the result before saving or sharing.", "The same precaution applies to a CSV workflow. Keep a source copy, check the column mapping and review any row where the bank or branch field no longer contains five digits."] },
      { heading: "Lookups need a source", paragraphs: ["Extracting codes does not confirm that they are currently assigned to the bank or branch described on an invoice. A verified directory may resolve them; an incomplete directory may not.", "IBANScan separates code extraction from directory matching. When banking data is unavailable, ask the bank or recipient for current details rather than relying on a guessed institution name.", "If you are investigating a rejected payment, give your provider the original payment reference through its secure support channel. A public IBAN tool cannot inspect the transfer or the account."] },
    ],
    faqs: [{ question: "Can I derive a bank name from ABI alone?", answer: "The ABI code can be matched against a reliable bank directory. The code itself is not a bank name, and IBANScan does not guess a match." }, { question: "Are ABI and CAB a BIC?", answer: "No. They are domestic identifiers in the Italian account format. A BIC is a separate international business identifier." }], sources: [sources.italy, sources.bic], tool: { label: "Find ABI and CAB", href: "/tools/abi-cab-checker" },
  },
  {
    slug: "iban-vs-bic", title: "IBAN vs BIC: what’s the difference?", description: "Compare an account's IBAN with an institution's BIC and learn which questions each identifier can answer.", category: "The essentials", readTime: "3 min read",
    sections: [
      { heading: "They identify different things", paragraphs: ["An IBAN expresses account details in a registered national format. A BIC identifies a business party, optionally with a branch or unit. Neither is a password, and neither by itself proves who owns an account.", "That distinction explains why the two identifiers sometimes appear together on payment instructions. One describes the account identifier; the other identifies a party involved in routing or processing the payment."] },
      { heading: "The practical comparison", paragraphs: ["IBAN length varies by country. It begins with a country prefix and international check digits. A BIC has eight characters, or eleven when the optional three-character branch identifier is present.", "IBAN validation can check a country-specific character pattern and checksum. BIC syntax can be inspected, but establishing that a code is assigned requires reference data. For both, syntax alone is weaker evidence than a verified directory entry."] },
      { heading: "What to put in a payment form", paragraphs: ["Enter the exact values supplied through the bank's or payment provider's official instructions. If your form asks for a BIC and you only have an IBAN, request the required routing information or use your provider's supported lookup.", "Do not enter the IBAN into the BIC field or choose a BIC because its letters resemble the bank's name. If a tool resolves a BIC, inspect its source and coverage; do not treat an unresolved lookup as permission to guess.", "IBANScan can explain the structural result and show available directory information. It cannot approve a transfer, guarantee arrival, recover a payment or confirm a recipient's identity."] },
    ],
    faqs: [{ question: "Do I always need both IBAN and BIC?", answer: "The required identifiers depend on the payment route and your provider. Follow the instructions shown by the provider handling the payment." }, { question: "Does a matching BIC prove account ownership?", answer: "No. An institution identifier does not establish the identity of the person or organization controlling an account." }], sources: [sources.swift, sources.bic], tool: { label: "Analyze an IBAN", href: "/tools/iban-analyzer" },
  },
];

export function getGuide(slug: string) { return guides.find((guide) => guide.slug === slug); }

export const countryEditorial: Record<string, { title: string; paragraphs: string[]; source?: { label: string; url: string } }> = {
  IT: { title: "Understanding ABI, CAB and CIN", paragraphs: ["Italy's national account format makes three local concepts visible: an alphabetic CIN control character, an ABI bank code and a CAB branch code. Keep each field intact, including leading zeros.", "The account field is twelve characters long. Its content is an identifier, not evidence of the account holder or available funds. The ABI/CAB tool helps separate these fields without suggesting an unverified bank name."], source: sources.italy },
  DE: { title: "Bankleitzahl and account conversion", paragraphs: ["Germany's national part combines an eight-digit bank sort code (Bankleitzahl) with a ten-digit account field. The complete IBAN has 22 characters.", "The Bundesbank notes that some institutions have specific account-conversion rules. Simply adding zeros and calculating new check digits is not a substitute for obtaining the correct IBAN from the bank."], source: sources.germany },
  FR: { title: "How an IBAN relates to a RIB", paragraphs: ["French account details are commonly presented on a RIB (relevé d'identité bancaire). The 27-character French IBAN contains the bank code, branch code, account field and domestic RIB key in its national portion.", "A RIB can carry additional information, but scanning the IBAN alone does not authenticate the document, its account holder or any accompanying payment instructions."], source: sources.france },
  ES: { title: "Bank, branch and domestic check digits", paragraphs: ["Spain's 24-character IBAN includes a four-digit institution code, a four-digit branch code, two domestic check digits and a ten-digit account field after its international prefix and check digits.", "The domestic control digits sit between the branch and account fields. Do not combine them with the account number or remove leading zeros when copying these fields into a spreadsheet."], source: sources.spain },
  NL: { title: "A visible four-letter bank identifier", paragraphs: ["The Netherlands uses an 18-character IBAN with a four-letter bank identifier followed by a ten-digit account field. A letter-to-digit transcription mistake in the bank field changes the national format.", "Recognizing a familiar four-letter sequence is not a live directory lookup. A resolved bank name and BIC still require a trustworthy mapping, and the account's owner is never inferred from the code."] },
  GB: { title: "The international form of UK account details", paragraphs: ["A United Kingdom IBAN contains 22 characters, including a four-letter bank identifier, a six-digit branch identifier (sort code) and an eight-digit account field.", "The sort code is part of the national layout, while the four-letter identifier is a separate field. UK geographical inclusion in SEPA concerns euro payment schemes; it does not mean every payment in pounds is a SEPA payment."] },
  CH: { title: "Country scope and account currency are different", paragraphs: ["Swiss IBANs contain 21 characters. Their national account layout includes a five-digit bank identifier and a twelve-character account field.", "Switzerland is within SEPA geographical scope while using the Swiss franc as its country currency. The CH prefix does not tell you which currencies a particular account accepts."] },
  BE: { title: "A compact national account format", paragraphs: ["Belgium's IBAN contains 16 characters. The national portion has twelve digits, including a three-digit bank identifier and domestic control digits.", "International check digits and domestic control fields are separate. Read the tool's validation details to see which checks were performed, and preserve the original national account formatting when comparing documents."] },
  IE: { title: "Bank and branch fields in an Irish IBAN", paragraphs: ["Ireland uses a 22-character IBAN. Its national portion begins with a four-letter bank identifier, followed by a six-digit branch code and an eight-digit account field.", "The IE prefix distinguishes the registered country layout. Do not change a prefix to make payment instructions resemble another country's account details; request corrected details from the bank instead."] },
  PT: { title: "National control digits remain part of the IBAN", paragraphs: ["A Portuguese IBAN has 25 characters. The national portion contains bank and branch identifiers, an account field and domestic control digits.", "Keep the entire national portion when formatting or validating. Extracted bank and branch codes are useful for interpretation but do not independently establish that a payment can be received."] },
};

export const legalPages: Record<string, { title: string; description: string; sections: ContentSection[] }> = {
  privacy: { title: "Privacy Policy", description: "How the default IBANScan application processes IBANs, AI questions and operational information.", sections: [
    { heading: "Basic validation", paragraphs: ["The browser can perform IBAN normalization, format checks, checksum checks and local bulk processing without saving your IBAN in an application database. The current application does not provide a persistent account-history feature. Results remain available in the current page until you reset it or close it.", "Features that call a server, including API validation and optional AI explanations, send the data needed for that request. Use only identifiers you are authorized to process. Do not include account-holder names, passwords or other unnecessary personal information."] },
    { heading: "Optional AI explanations", paragraphs: ["AI explanations require a configured external provider. When you choose this feature, the backend sends your question and a minimized technical validation summary to that provider. The full account identifier should not be included in the technical summary. Avoid entering an IBAN or personal information into the question itself.", "The operator must identify the enabled provider, processing locations, retention terms and applicable data arrangements before enabling this feature publicly."] },
    { heading: "Operational data and optional services", paragraphs: ["The server uses request metadata to enforce security and rate limits. Hosting and network providers may process connection information under their own operational settings. Application analytics are optional and should receive only predefined events without full IBANs.", "Advertising is disabled unless configured. Any future advertising, analytics or account-history provider must be reflected in this notice and in the deployment's consent controls before activation."] },
    { heading: "Your choices and contact", paragraphs: ["Basic scanning does not require registration. Clear the current input with the reset control and avoid sharing a result if it contains account details you do not want to disclose. The contact page shows the operator contact when configured.", "This draft must be completed with the operator's identity, lawful processing basis where applicable, retention periods, hosting details, rights procedures and contact information before public launch."] },
  ] },
  cookies: { title: "Cookie Policy", description: "Storage choices and optional integrations in the default IBANScan application.", sections: [
    { heading: "Current storage", paragraphs: ["When you select a language, the site stores your choice in the first-party ibanscan-locale cookie for one year. This preference cookie contains only the selected language code and applies across the site. It uses SameSite=Lax and the Secure attribute on HTTPS connections. It is not an advertising identifier and does not contain an IBAN.", "The selected appearance is stored in your browser's localStorage as ibanscan-theme until you change it or clear the site's stored data. You can change language and appearance using the interface controls, or remove their saved values in your browser's site settings. Basic IBAN validation does not require an advertising cookie or an account login.", "The application is designed without a required third-party analytics or advertising integration. Its future authentication or billing features may introduce additional storage requirements."] },
    { heading: "Optional advertising and analytics", paragraphs: ["Before enabling services that use non-essential cookies or similar technologies, the operator must document each service, its purpose, duration and available controls. Consent must be obtained where applicable and withdrawal must be supported.", "No consent banner should suggest an advertising integration is active when none is configured. Conversely, a configured integration must not start storing non-essential identifiers merely because a placeholder ad component exists."] },
    { heading: "Deployment-specific notice", paragraphs: ["The operator must audit the final deployed site, including hosting, consent tools and any embedded providers, and update this page with the actual technologies used. This page describes the default application and is not a completed deployment-specific cookie inventory."] },
  ] },
  terms: { title: "Terms of Service", description: "Scope, permitted use and limitations of the IBANScan technical validation service.", sections: [
    { heading: "Service scope", paragraphs: ["IBANScan provides technical tools for interpreting IBAN structure and available reference information. It does not open accounts, hold funds, initiate payments or provide account-ownership verification. Its educational content is not personalized financial, legal or banking advice."] },
    { heading: "Responsible use", paragraphs: ["Only submit data you are entitled to process. Do not use the service to probe accounts, collect personal information, evade rate limits, attack infrastructure or misrepresent validation results as proof of account ownership.", "Keep API credentials confidential. Automated access must use the supported authenticated API and respect the configured limits. A successful validation response is not authorization to debit, credit or access an account."] },
    { heading: "Results and availability", paragraphs: ["Formats, banking directories and payment-scheme coverage can change. Reference data may be incomplete or unavailable. Verify payment instructions and time-sensitive information with the relevant provider.", "The initial product does not sell subscriptions or guarantee service levels. Any future paid service needs its own published commercial terms and billing disclosures."] },
    { heading: "Operator details pending", paragraphs: ["The operator must complete these draft terms with its legal identity, contact, applicable jurisdiction, consumer provisions and any appropriate service-specific obligations before launch. No governing law, liability waiver or contractual remedy is invented in this draft."] },
  ] },
  disclaimer: { title: "Disclaimer", description: "What IBANScan validates, what verified bank data means, and what these tools cannot establish.", sections: [
    { heading: "A format check is a limited check", paragraphs: ["IBANScan checks IBAN structure and available banking data. It does not confirm account ownership, account balance, or whether an account is currently active.", "A valid result means the implemented length, national structure and international checksum checks passed. It is not evidence that a recipient is trustworthy or that a transfer will succeed."] },
    { heading: "Bank data and SEPA", paragraphs: ["A bank name or BIC is shown only where a configured source provides a match. Missing information is reported as unavailable. Extracted bank and branch identifiers are calculated fields, not independently confirmed banking relationships.", "SEPA labels describe the country-level geographical scope stored in the dataset. They do not guarantee a particular institution's participation in a scheme or a specific account's payment capabilities."] },
    { heading: "AI and generated examples", paragraphs: ["AI explanations interpret the supplied technical result and may contain mistakes. They are not a replacement for the structured validation output or information from your bank.", "Examples and generated IBANs are for understanding formats or testing software. They do not create accounts and must not be used as payment instructions."] },
  ] },
};
