export type ToolKind = "scanner" | "formatter" | "generator" | "country" | "bank" | "bulk";
export const toolCatalog: { slug: string; name: string; description: string; detail: string; group: string; icon: string; kind: ToolKind }[] = [
  { slug: "iban-validator", name: "IBAN Validator", description: "A quick, thorough check of any IBAN.", detail: "Check country format, length and international check digits, privately in your browser.", group: "IBAN tools", icon: "scan", kind: "scanner" },
  { slug: "iban-analyzer", name: "IBAN Analyzer", description: "Understand every part of an IBAN.", detail: "Break an IBAN into its country, check digits and domestic identifiers, with sourced bank data where available.", group: "IBAN tools", icon: "layers", kind: "scanner" },
  { slug: "iban-formatter", name: "IBAN Formatter", description: "Clean, readable, ready to copy.", detail: "Remove whitespace, capitalize letters and format an IBAN for reading or electronic use.", group: "IBAN tools", icon: "text", kind: "formatter" },
  { slug: "iban-generator", name: "IBAN Generator", description: "Calculate an IBAN from a known BBAN.", detail: "Calculate international check digits for bank-supplied domestic account details. No accounts are created.", group: "IBAN tools", icon: "code", kind: "generator" },
  { slug: "iban-country-checker", name: "IBAN Country Checker", description: "Find the country behind the prefix.", detail: "Look up national IBAN length, domestic structure and SEPA geographical coverage by country code.", group: "IBAN tools", icon: "globe", kind: "country" },
  { slug: "bic-swift-finder", name: "BIC / SWIFT Finder", description: "Look up verified bank identifiers.", detail: "Search source-backed bank records and check the syntax of a BIC. Unverified information is never guessed.", group: "Banking tools", icon: "building", kind: "bank" },
  { slug: "bank-identifier-finder", name: "Bank Identifier Finder", description: "Extract the bank code from an IBAN.", detail: "Read a national bank identifier from its country-specific position. A code alone does not confirm a bank’s identity.", group: "Banking tools", icon: "landmark", kind: "scanner" },
  { slug: "abi-cab-checker", name: "Italy ABI / CAB Finder", description: "Find Italian bank and branch codes.", detail: "Extract the five-digit ABI bank identifier and five-digit CAB branch identifier from an Italian IBAN.", group: "Banking tools", icon: "map", kind: "scanner" },
  { slug: "sepa-checker", name: "SEPA Checker", description: "Check a country’s SEPA coverage.", detail: "Check whether an IBAN’s country is within SEPA’s geographical scope. Bank participation requires a separate check.", group: "Banking tools", icon: "globe", kind: "scanner" },
  { slug: "bulk-iban-validator", name: "Bulk IBAN Validator", description: "Check a whole list in one go.", detail: "Validate up to 100 IBANs at a time on your device and export a clear, spreadsheet-ready report.", group: "Business tools", icon: "list", kind: "bulk" },
  { slug: "csv-iban-validator", name: "CSV IBAN Validator", description: "Turn a spreadsheet into clear results.", detail: "Open a CSV locally, validate its IBAN column and download your results. Your file is never uploaded.", group: "Business tools", icon: "file", kind: "bulk" },
];
export const getTool = (slug: string) => toolCatalog.find((tool) => tool.slug === slug);
