-- PostgreSQL foundation for a future authenticated Business release.
-- Not applied or required by the current stateless application.
-- UUIDs are generated by the future identity/persistence service.
-- Never add IBAN, BBAN, account-number, prompt, or raw request-body columns.

BEGIN;

CREATE TABLE organizations (
  id uuid PRIMARY KEY,
  name text NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE app_users (
  id uuid PRIMARY KEY,
  identity_subject text UNIQUE NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE organization_memberships (
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('owner', 'admin', 'member')),
  PRIMARY KEY (organization_id, user_id)
);

CREATE TABLE subscriptions (
  organization_id uuid PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
  plan text NOT NULL DEFAULT 'free' CHECK (plan IN ('free', 'pro', 'business')),
  status text NOT NULL DEFAULT 'inactive' CHECK (status IN ('inactive', 'active', 'past_due', 'canceled')),
  billing_customer_ref text UNIQUE,
  billing_subscription_ref text UNIQUE,
  period_ends_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE api_keys (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  label text NOT NULL CHECK (length(label) BETWEEN 1 AND 100),
  key_hash char(64) UNIQUE NOT NULL CHECK (key_hash ~ '^[a-f0-9]{64}$'),
  display_prefix varchar(12) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  revoked_at timestamptz
);

CREATE TABLE daily_api_usage (
  api_key_id uuid NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
  usage_date date NOT NULL,
  operation text NOT NULL CHECK (operation IN ('validate', 'analyze', 'bank_search')),
  request_count bigint NOT NULL DEFAULT 0 CHECK (request_count >= 0),
  error_count bigint NOT NULL DEFAULT 0 CHECK (error_count >= 0),
  PRIMARY KEY (api_key_id, usage_date, operation)
);

CREATE TABLE bank_datasets (
  id uuid PRIMARY KEY,
  name text NOT NULL,
  source_url text NOT NULL CHECK (source_url LIKE 'https://%'),
  license_notes text NOT NULL,
  verified_at timestamptz NOT NULL,
  expires_at timestamptz,
  active boolean NOT NULL DEFAULT false
);

CREATE TABLE bank_records (
  dataset_id uuid NOT NULL REFERENCES bank_datasets(id) ON DELETE CASCADE,
  country_code char(2) NOT NULL CHECK (country_code ~ '^[A-Z]{2}$'),
  bank_identifier varchar(12) NOT NULL,
  name text NOT NULL,
  bic varchar(11) CHECK (bic ~ '^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$'),
  PRIMARY KEY (dataset_id, country_code, bank_identifier)
);

CREATE TABLE admin_roles (
  user_id uuid PRIMARY KEY REFERENCES app_users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('content_editor', 'data_editor', 'administrator')),
  granted_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE admin_audit_events (
  id uuid PRIMARY KEY,
  actor_id uuid NOT NULL REFERENCES app_users(id),
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX admin_audit_events_recent ON admin_audit_events (occurred_at DESC);

-- Store non-secret published content/configuration only. AI/API/database secrets
-- remain in the deployment secret manager, never this JSON document.
CREATE TABLE managed_configuration (
  key text PRIMARY KEY CHECK (key IN ('country_data', 'content', 'faq', 'advertising', 'ai_model', 'api_limits')),
  document jsonb NOT NULL,
  revision bigint NOT NULL DEFAULT 1,
  updated_by uuid NOT NULL REFERENCES app_users(id),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Identity/tenant authorization must be added and tested before connecting a UI.
-- RLS fails closed for a non-owner application role until explicit policies exist.
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_api_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE bank_datasets ENABLE ROW LEVEL SECURITY;
ALTER TABLE bank_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE managed_configuration ENABLE ROW LEVEL SECURITY;

COMMIT;

