import { getLocale } from "@/lib/i18n-server";
import { apiCopy } from "@/lib/api-copy";
import Link from "next/link";
import { analyzeIban } from "@/lib/iban";
import { pageMetadata, siteUrl } from "@/lib/seo";

export const metadata = pageMetadata("API documentation", "Authentication, request examples, validation fields, bank-search parameters, rate-limit headers and errors for the IBANScan v1 API.", "/api/docs");

const example = analyzeIban("IT60X0542811101000000123456");
const validationExample = { valid: example.valid, normalized: example.normalized, country: example.country ? { code: example.country.code, name: example.country.name } : null, checks: example.checks, errors: example.errors };
const statuses = [
  ["200", "Request processed", "Inspect valid for IBAN checks. A structurally invalid IBAN still returns a successful analysis response."],
  ["400", "Invalid request", "Check JSON shape, the IBAN string or bank-search parameters."],
  ["401", "Unauthorized", "Supply a valid Bearer key. Never publish the key in client-side code."],
  ["413", "Payload too large", "Keep the request within the 4,096-byte JSON-body limit."],
  ["415", "Unsupported content type", "Send POST requests as application/json."],
  ["429", "Rate limited", "Wait for the number of seconds in Retry-After before retrying."],
  ["500", "Request failed", "An unexpected server failure occurred. Retry cautiously; no internal details are exposed."],
  ["503", "Not configured or unavailable", "The API key configuration or required request-protection service is unavailable. Contact the deployment operator."],
];

export default async function ApiDocsPage() {
 const locale=await getLocale();
  const base = `${siteUrl()}/api/v1`;
  const curl = `curl --request POST '${base}/iban/validate' \\\n  --header "Authorization: Bearer $IBANSCAN_API_KEY" \\\n  --header 'Content-Type: application/json' \\\n  --data '{"iban":"IT60X0542811101000000123456"}'`;
  const javascript = `// Run on your server. Never expose the key in a browser bundle.\nconst response = await fetch("${base}/iban/analyze", {\n  method: "POST",\n  headers: {\n    Authorization: \`Bearer \${process.env.IBANSCAN_API_KEY}\`,\n    "Content-Type": "application/json",\n  },\n  body: JSON.stringify({ iban: "IT60X0542811101000000123456" }),\n  cache: "no-store",\n});\nconst result = await response.json();\nif (!response.ok) throw new Error(result.error);\n// result.valid describes the IBAN; HTTP status describes the request.`;
  return <div className="page-shell" lang="en">{locale!=="en"&&<p className="editorial-language-note" lang={locale}>{apiCopy[locale].docsNote}</p>}<nav aria-label="Breadcrumb" className="breadcrumbs"><Link href="/api">API</Link><span aria-hidden="true"> / </span><span>Documentation</span></nav><header className="page-heading"><p className="eyebrow">Developer reference / v1</p><h1>From input to insight.</h1><p className="muted">Authenticated JSON endpoints with explicit validation results and honest data availability.</p></header>
    <nav aria-label="Documentation sections" className="doc-links"><Link href="#authentication">Authentication</Link><Link href="#validate">Validation</Link><Link href="#analyze">Analysis</Link><Link href="#banks">Bank search</Link><Link href="#errors">Errors & limits</Link></nav>
    <article className="article wide-article">
      <section id="authentication"><h2>Authentication</h2><p>Send <code>Authorization: Bearer YOUR_API_KEY</code> on every v1 request. The deployment operator issues keys and assigns plan limits. Self-service key creation is not part of this release.</p><p>Keys must contain 32–256 URL-safe letters, digits, underscores or hyphens. The server stores SHA-256 digests in its private <code>IBANSCAN_API_KEY_HASHES</code> configuration. Never include a key in a URL, commit it to source control or put it in a public environment variable.</p><p>These endpoints are intended for server-to-server integration. The interactive playground sends a key only to this deployment and keeps it in page memory; it does not make a private key safe to embed in a public application.</p><p>Base URL: <code>{base}</code></p></section>
      <section id="validate"><h2>Validate an IBAN</h2><p><span className="tag">POST</span> <code>/api/v1/iban/validate</code></p><p>Send a JSON object with a non-empty <code>iban</code> string of at most 128 input characters. Whitespace is removed and ASCII letters are uppercased. Unexpected punctuation is retained and produces a validation failure.</p><pre className="code-block"><code>{curl}</code></pre><p>The following response uses a published format example. It is not a payment instruction.</p><details className="card"><summary>View the complete validation response</summary><pre className="code-block"><code>{JSON.stringify(validationExample, null, 2)}</code></pre></details>
        <div className="table-scroll" tabIndex={0} role="region" aria-label="Validation response fields"><table className="data-table"><thead><tr><th scope="col">Field</th><th scope="col">Type</th><th scope="col">Meaning</th></tr></thead><tbody>
          <tr><th scope="row"><code>valid</code></th><td>boolean</td><td>All implemented format, length, structure and international checksum checks passed.</td></tr><tr><th scope="row"><code>normalized</code></th><td>string</td><td>Uppercase input without whitespace. Treat it as sensitive data.</td></tr><tr><th scope="row"><code>country</code></th><td>object | null</td><td>Detected country code and name, or null when unsupported.</td></tr><tr><th scope="row"><code>checks</code></th><td>array</td><td>Each check has id, label, passed and message fields.</td></tr><tr><th scope="row"><code>errors</code></th><td>string[]</td><td>Messages for failed checks; empty when valid.</td></tr>
        </tbody></table></div><p>A <code>200</code> response with <code>valid: false</code> means validation completed and found problems. Do not retry an unchanged invalid IBAN as if it were a network error.</p></section>
      <section id="analyze"><h2>Analyze an IBAN</h2><p><span className="tag">POST</span> <code>/api/v1/iban/analyze</code></p><p>Accepts the same request body and returns the full engine result directly, without a <code>data</code> wrapper. The country object includes its format definition, example, notes and extraction offsets. Those offsets are zero-based within the BBAN.</p><pre className="code-block"><code>{javascript}</code></pre><h3>Additional result fields</h3><ul><li><code>formatted</code>: groups the normalized identifier into four-character blocks.</li><li><code>masked</code>: a display mask; this is not an anonymization guarantee.</li><li><code>bban</code>: the national portion after the first four characters.</li><li><code>bankIdentifier</code>, <code>branchIdentifier</code>, <code>accountIdentifier</code>: extracted strings or null where unavailable.</li><li><code>bank</code>: a verified dataset record or null. Any record includes its source and verification date; a BIC may be absent.</li><li><code>sepa</code>: true or false for the configured country-level scope, or null when no supported country is detected.</li></ul><p>Identifiers may be extractable even when the international checksum fails, provided the national layout is otherwise well-formed. A bank record is only resolved for an IBAN that passes all checks.</p><p>SEPA geography does not establish bank participation. Some territories share a country prefix, so territorial coverage can require additional information. None of these fields verifies an account owner, active status or balance.</p></section>
      <section id="banks"><h2>Search the banking dataset</h2><p><span className="tag">GET</span> <code>/api/v1/bank/search?q=MARK&amp;country=DE</code></p><p><code>q</code> is required and must contain 2–80 characters after trimming. <code>country</code> is an optional two-letter country code. Pass URL-encoded search text. Search returns at most 20 records.</p><pre className="code-block"><code>{JSON.stringify({ banks: [], count: 0, message: "Bank information unavailable" }, null, 2)}</code></pre><p>An empty array is a valid result. It does not establish that a bank is fictitious or inactive; the configured directory may simply lack the requested mapping. Inspect the source and verification date of returned records before using them.</p></section>
      <section id="errors"><h2>Errors and request limits</h2><p>Errors return a JSON object such as <code>{'{"error":"A valid API key is required."}'}</code>. They do not expose a stack trace or echo credentials.</p><div className="table-scroll" tabIndex={0} role="region" aria-label="API HTTP status codes"><table className="data-table"><thead><tr><th scope="col">Status</th><th scope="col">Meaning</th><th scope="col">Next step</th></tr></thead><tbody>{statuses.map(([code, meaning, action]) => <tr key={code}><th scope="row">{code}</th><td>{meaning}</td><td>{action}</td></tr>)}</tbody></table></div><p>Successful authenticated responses expose <code>X-RateLimit-Limit</code>, <code>X-RateLimit-Remaining</code> and <code>X-RateLimit-Reset</code>. Reset is a Unix timestamp in seconds. Limits depend on the configured plan, so clients should read these headers rather than assume a fixed allowance. A <code>429</code> also includes <code>Retry-After</code> in seconds.</p><p>Production deployments need configured request protection. If that protection is unavailable, requests fail closed instead of bypassing the limit.</p></section>
      <section><h2>Handle financial identifiers carefully</h2><p>Keep full IBANs and credentials out of access URLs, analytics and diagnostic logs. API responses are marked <code>no-store</code>. The service does not persist submitted IBANs in an application database; your infrastructure and client still need appropriate logging and retention settings.</p><p><Link className="button primary" href="/api/playground">Try a request in the playground →</Link></p></section>
    </article>
  </div>;
}
